//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <fcntl.h>
#include <sched.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// --------------------- Global Variables ---------------------

int64_t g1 = 0x12a0; // 0x3dd8
int64_t g2 = 0x1260; // 0x3de0
int64_t g3 = 0; // 0x3ff8
char * g4[2] = {
    "(eU8Z7HoOn<E6C(`(r&GU'RP`e1",
    "84W[WiI.GbI=['S+oc]piSCN(f"
}; // 0x40e8

// ------------------------ Functions -------------------------

// Address range: 0x12a5 - 0x12ef
int64_t function_12a5(int64_t a1, int64_t a2) {
    int32_t v1 = (0x1000000 * (int32_t)a1 >> 24) - 64 + (0x1000000 * (int32_t)a2 >> 24); // 0x12d1
    return (0x100000000 * (int64_t)(v1 >> 31) | (int64_t)v1) % 95 + 32 & 0xffffffff;
}

// Address range: 0x18a3 - 0x1bf6
int64_t function_18a3(char *str, int32_t len) {
    printf("{");
    for (int64_t v2 = 0; v2 < (int64_t)len; v2++) {
        // 0x1b66
        char * v5 = (char *)(str + v2);
        char v6 = *(char *)(str + v2);
        *v5 = function_12a5((int64_t)v6 & 0xffffffff, (int64_t)*v5 & 0xffffffff);
        printf(" %d,", (unsigned int) (unsigned char) *v5);
    }
    printf("}\n");
    int32_t strncmp_rc = strncmp(str, g4[0], len); // 0x1bc6
    if (strncmp_rc != 0) {
        // 0x1be5
        puts("Failed !");
    }
    // 0x1bf1
    return strncmp_rc != 0 ? 0xffffffff : 0;
}

int main() {
    char tmp[256] = {0};
    for(int i = 0; i < 256; i++) {
      tmp[i] = (char)i;
    }
    return function_18a3(tmp, 256);
}
